// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID                pgtype.UUID `json:"id"`
	Email             *string     `json:"email"`
	DisplayName       *string     `json:"display_name"`
	AvatarUrl         *string     `json:"avatar_url"`
	PreferredLanguage string      `json:"preferred_language"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
}
