// Code generated by sqlc. DO NOT EDIT.
// source: profiles.sql
package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ?? GetProfileByID ????????????????????????????????????????????????????????????

const getProfileByID = `-- name: GetProfileByID :one
select id, email, display_name, avatar_url, preferred_language, created_at, updated_at
from profiles
where id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID, &i.Email, &i.DisplayName, &i.AvatarUrl,
		&i.PreferredLanguage, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

// ?? CreateProfile ?????????????????????????????????????????????????????????????

const createProfile = `-- name: CreateProfile :one
insert into profiles (id, email, preferred_language)
values ($1, $2, 'zh-TW')
returning id, email, display_name, avatar_url, preferred_language, created_at, updated_at
`

type CreateProfileParams struct {
	ID    pgtype.UUID `json:"id"`
	Email *string     `json:"email"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.ID, arg.Email)
	var i Profile
	err := row.Scan(
		&i.ID, &i.Email, &i.DisplayName, &i.AvatarUrl,
		&i.PreferredLanguage, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
update profiles
set display_name       = coalesce($2, display_name),
    avatar_url         = coalesce($3, avatar_url),
    preferred_language = coalesce($4, preferred_language),
    updated_at         = now()
where id = $1
returning id, email, display_name, avatar_url, preferred_language, created_at, updated_at
`

type UpdateProfileParams struct {
	ID                pgtype.UUID `json:"id"`
	DisplayName       *string     `json:"display_name"`
	AvatarUrl         *string     `json:"avatar_url"`
	PreferredLanguage *string     `json:"preferred_language"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID, arg.DisplayName, arg.AvatarUrl, arg.PreferredLanguage,
	)
	var i Profile
	err := row.Scan(
		&i.ID, &i.Email, &i.DisplayName, &i.AvatarUrl,
		&i.PreferredLanguage, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}
